version: '3'
services:
  web:
    image: nginx:1.18
    ports:
      - 8000:80
    links:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    links:
      - mysql
      - redis
  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
    volumes:
      - redis:/data"
volumes:
  mysql:
    driver: local
  redis:
    driver: local